name       : libpcre3
version    : 8.39
release    : 11
source     :
    - ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.39.tar.gz : ccdf7e788769838f8285b3ee672ed573358202305ee361cfec7a4a4fb005bbc7
license    :
    - BSD-3-Clause
summary    : Steam Compatibility Library
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
    - bzip2-32bit-devel
    - libstdc++-32bit
    - pkgconfig32(zlib)
optimize   : speed
component  : binary.comat
emul32     : yes
description: |
    Provides Steam Binary Compatibility. It is NOT permitted to link against this package within Solus
setup      : |
    %patch -p1 < $pkgfiles/0001-Butcher-soname-to-enable-building-of-libpcre3.patch
    %reconfigure --enable-unicode-properties \
               --enable-pcregrep-libz \
               --enable-pcregrep-libbz2 \
               --enable-jit \
               --disable-static \
               --enable-pcre16 \
               --enable-pcre32 \
               --disable-cpp \
               --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    # Make it impossible to build against this package
    rm -vrf $installdir/usr/include
    rm -vrf $installdir/%libdir%/pkgconfig
    rm -v $installdir/%libdir%/*.so
    
    
    # Binaries are in main libpcre
    rm -rfv $installdir/usr/bin
    rm -rfv $installdir/usr/share
