name       : libpcre3
version    : '8.40'
release    : 13
source     :
    - ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.40.tar.gz : 1d75ce90ea3f81ee080cdc04e68c9c25a9fb984861a0618be7bbf676b18eda3e
license    : BSD-3-Clause
summary    : Steam Compatibility Library
builddeps  :
    - bzip2-32bit-devel
    - pkgconfig32(zlib)
optimize   : speed
component  : binary.comat
emul32     : yes
description: |
    Provides Steam Binary Compatibility. It is NOT permitted to link against this package within Solus
setup      : |
    %patch -p1 < $pkgfiles/0001-Butcher-soname-to-enable-building-of-libpcre3.patch
    %patch -p2 < $pkgfiles/security/cve-2017-7186.patch
    %reconfigure --enable-unicode-properties \
               --enable-pcregrep-libz \
               --enable-pcregrep-libbz2 \
               --enable-jit \
               --disable-static \
               --enable-pcre16 \
               --enable-pcre32 \
               --disable-cpp \
               --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    # Make it impossible to build against this package
    rm -vrf $installdir/usr/include
    rm -vrf $installdir/%libdir%/pkgconfig
    rm -v $installdir/%libdir%/*.so


    # Binaries are in main libpcre
    rm -rfv $installdir/usr/bin
    rm -rfv $installdir/usr/share
